In [19]:
import pandas as pd

In [20]:
df = pd.read_pickle("../Cleaned_datasets/cleaned_df_altitude_of_municipalities.pkl")
df_1 = pd.read_pickle("../Cleaned_datasets/cleaned_df_covid_province.pkl")

In [21]:
# Filter for Region = Lazio i.e Regional Code = 12
Lazio_df = df[df["Region_Code"] == 12]

In [22]:
# Count, in a new DataFrame, the number of municipalities (Name)
# and their average altitude (Average) in each province (Province_Code)

result = Lazio_df.groupby("Province_Code").agg(
    Municipality_Count=("Name", "count"),
    Average_Altitude=("Average", "mean")
).reset_index()

In [23]:
print (result)

   Province_Code  Municipality_Count  Average_Altitude
0             56                  60        310.747529
1             57                  73        656.248891
2             58                 121        393.691390
3             59                  33        249.895877
4             60                  91        485.413442

In [24]:
df3 = df_1[df_1['Region']=='Lazio']
# Rename column in df3 (cleaned Lazio Covid_province) to match 'result' dataframe column name
df3 = df3.rename(columns={"ProvinceCode": "Province_Code"})
df3.head()

,Date,Country,RegionCode,Region,Province_Code,ProvinceName,ProvinceAbbreviation,Latitude,Longitude,TotalPositiveCases
28,2020-02-24,ITA,12,Lazio,56,Viterbo,VT,42.417383,12.104734,0
29,2020-02-24,ITA,12,Lazio,57,Rieti,RI,42.404884,12.862059,0
30,2020-02-24,ITA,12,Lazio,58,Roma,RM,41.892770,12.483667,0
31,2020-02-24,ITA,12,Lazio,59,Latina,LT,41.467595,12.903685,0
32,2020-02-24,ITA,12,Lazio,60,Frosinone,FR,41.639646,13.351172,0

In [25]:
# Merge Lazio Covid Province and result on province code to have the province name
merged = result.merge(df3, on="Province_Code")

merged.head()

,Province_Code,Municipality_Count,Average_Altitude,Date,Country,RegionCode,Region,ProvinceName,ProvinceAbbreviation,Latitude,Longitude,TotalPositiveCases
0,56,60,310.747529,2020-02-24,ITA,12,Lazio,Viterbo,VT,42.417383,12.104734,0
1,56,60,310.747529,2020-02-25,ITA,12,Lazio,Viterbo,VT,42.417383,12.104734,0
2,56,60,310.747529,2020-02-26,ITA,12,Lazio,Viterbo,VT,42.417383,12.104734,0
3,56,60,310.747529,2020-02-27,ITA,12,Lazio,Viterbo,VT,42.417383,12.104734,0
4,56,60,310.747529,2020-02-28,ITA,12,Lazio,Viterbo,VT,42.417383,12.104734,0

In [26]:
# Merge Lazio Covid Province and result on province code to have the province name
merged = result.merge(df3, on="Province_Code")

merged.head()

,Province_Code,Municipality_Count,Average_Altitude,Date,Country,RegionCode,Region,ProvinceName,ProvinceAbbreviation,Latitude,Longitude,TotalPositiveCases
0,56,60,310.747529,2020-02-24,ITA,12,Lazio,Viterbo,VT,42.417383,12.104734,0
1,56,60,310.747529,2020-02-25,ITA,12,Lazio,Viterbo,VT,42.417383,12.104734,0
2,56,60,310.747529,2020-02-26,ITA,12,Lazio,Viterbo,VT,42.417383,12.104734,0
3,56,60,310.747529,2020-02-27,ITA,12,Lazio,Viterbo,VT,42.417383,12.104734,0
4,56,60,310.747529,2020-02-28,ITA,12,Lazio,Viterbo,VT,42.417383,12.104734,0

In [27]:
merged_cov_prov_and_alt_mun = merged
merged_cov_prov_and_alt_mun.to_pickle("../Cleaned_datasets/merged_cov_prov_and_alt_mun.pkl")